stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./app.Dockerfile
      buildContext: .
      tag: netcdf_editor:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - main
  exclude:
  - gh-pages
notification: {}
