stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./services/flask/Dockerfile
      buildContext: Multi_Page_WebApp
      tag: netcdf_editor_flask_app:${CICD_EXECUTION_SEQUENCE}
  - publishImageConfig:
      dockerfilePath: ./services/panel/Dockerfile
      buildContext: Multi_Page_WebApp
      tag: netcdf_editor_panel_app:${CICD_EXECUTION_SEQUENCE}
  - publishImageConfig:
      dockerfilePath: ./services/nginx/Dockerfile
      buildContext: Multi_Page_WebApp
      tag: netcdf_editor_nginx_app:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - main
  - flask
  - flask-docker-refactor
  exclude:
  - gh-pages
notification: {}
