stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./app.Dockerfile
      buildContext: .
      tag: netcdf_editor:latest
      registry: 127.0.0.1:34368
timeout: 60
notification: {}
