stages:
- name: Publish
  steps:
  - runScriptConfig:
      image: docker/compose
      shellScript: docker-compose --env-file ./config/.env.prod up --build
branch:
  include:
  - main
  - flask
  - flask-docker-refactor
  exclude:
  - gh-pages
notification: {}
