kind: Service
apiVersion: v1
metadata:
  name: netcdf-editor-service
spec:
  selector:
    app: netcdf
  type: NodePort
  ports:
    - protocol: TCP
      port: 42212
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcdf-editor
  labels:
    app: netcdfeditor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcdfeditor
  template:
    metadata:
      labels:
        app: netcdfeditor
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: netcdfeditor
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
