version: '3'
services:
  nginx:
    build: Multi_Page_WebApp/services/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on: 
      - flask_app
      - panel_app
    
  flask_app:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/flask/Dockerfile
    env_file: ${FLASK_CONFIG}
    environment: 
      PANEL_HOST: 127.0.0.1
      PANEL_SOCKET: ${NGINX_PORT}
    image: netcdf_editor_flask_app:latest 
    expose:
      - 5000
    entrypoint: gunicorn --bind 0.0.0.0:5000 "netcdf_editor_app:create_app()"
    # entrypoint: python -m flask run
    volumes:
      - instance_storage:/usr/src/app/instance
  
  panel_app:
    build:
      context: Multi_Page_WebApp
      dockerfile: services/panel/Dockerfile
    env_file: ${PANEL_CONFIG}
    image: netcdf_editor_panel_app:latest
    expose: 
      - 5006
    volumes:
      - instance_storage:/usr/src/app/instance

volumes:
  instance_storage:

