version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file: ${FLASK_CONFIG}
    image: netcdf_editor:latest 
    ports:
     - "8080:5000"
    volumes:
      - instance_storage:/usr/src/app/instance
  
  panel_apps:
    build:
      context: .
      dockerfile: panel_apps.Dockerfile
    image: netcdf_editor_panel_apps:latest
    ports:
      - "9090:5006"
    volumes:
      - instance_storage:/usr/src/app/instance

volumes:
  instance_storage:

