# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
    branches:
      - main
    paths:
    - .github/workflows/python-app-flask-test.yml
    - 'Multi_Page_WebApp/flask_app/'
    - 'Multi_Page_WebApp/python_tools/'
    - 'Multi_Page_WebApp/tests/'
    - '!**/*.md'
    
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/python-app-flask-test.yml
      - 'Multi_Page_WebApp/flask_app/'
      - 'Multi_Page_WebApp/python_tools/'
      - 'Multi_Page_WebApp/tests/'
      - '!**/*.md'

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        if [ -f Multi_Page_WebApp/requirements.txt ]; then pip install -r Multi_Page_WebApp/requirements.txt; fi
    - name: Install Packages 
      run: |
        pip install Multi_Page_WebApp/flask_app
        pip install Multi_Page_WebApp/python_tools
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd Multi_Page_WebApp 
        coverage run -m pytest tests/ && coverage report